/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TinhNangRouteImport } from './routes/tinh-nang'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BangGiaRouteImport } from './routes/bang-gia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRightyRouteImport } from './routes/api/righty'

const TinhNangRoute = TinhNangRouteImport.update({
  id: '/tinh-nang',
  path: '/tinh-nang',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BangGiaRoute = BangGiaRouteImport.update({
  id: '/bang-gia',
  path: '/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRightyRoute = ApiRightyRouteImport.update({
  id: '/api/righty',
  path: '/api/righty',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/blog': typeof BlogRoute
  '/tinh-nang': typeof TinhNangRoute
  '/api/righty': typeof ApiRightyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/blog': typeof BlogRoute
  '/tinh-nang': typeof TinhNangRoute
  '/api/righty': typeof ApiRightyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/blog': typeof BlogRoute
  '/tinh-nang': typeof TinhNangRoute
  '/api/righty': typeof ApiRightyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bang-gia' | '/blog' | '/tinh-nang' | '/api/righty'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bang-gia' | '/blog' | '/tinh-nang' | '/api/righty'
  id: '__root__' | '/' | '/bang-gia' | '/blog' | '/tinh-nang' | '/api/righty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangGiaRoute: typeof BangGiaRoute
  BlogRoute: typeof BlogRoute
  TinhNangRoute: typeof TinhNangRoute
  ApiRightyRoute: typeof ApiRightyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tinh-nang': {
      id: '/tinh-nang'
      path: '/tinh-nang'
      fullPath: '/tinh-nang'
      preLoaderRoute: typeof TinhNangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-gia': {
      id: '/bang-gia'
      path: '/bang-gia'
      fullPath: '/bang-gia'
      preLoaderRoute: typeof BangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/righty': {
      id: '/api/righty'
      path: '/api/righty'
      fullPath: '/api/righty'
      preLoaderRoute: typeof ApiRightyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangGiaRoute: BangGiaRoute,
  BlogRoute: BlogRoute,
  TinhNangRoute: TinhNangRoute,
  ApiRightyRoute: ApiRightyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
